name: "Code freeze"
description: "Util for setting a code freeze in a repo"
author: "goodwater cap"

# Define your inputs here.
inputs:
  codefreeze-begin:
    description: "The date when the code freeze begins. Note that this is inclusive, and in UTC. Format: YYYY-MM-DDTHH:MM:SSZ"
    required: true
  codefreeze-end:
    description: "The date when the code freeze end. Note that this is inclusive, and in UTC. Format: YYYY-MM-DDTHH:MM:SSZ"
    required: true
  allowed-paths:
    description: "The paths that are allowed to be modified during the code freeze. Multiple paths should be separated by newlines, i.e. |- in YAML."
    required: false
  token:
    description: >
      GitHub token for GitHub API requests.
      Users shouldn't need to set this themselves.
    required: true
    default: ${{ github.token }}

runs:
  using: node20
  main: dist/index.js
