name: "Code freeze"
description: "Util for setting a code freeze in a repo"
author: "goodwater cap"

# Define your inputs here.
inputs:
  codefreeze-begin:
    description: "The date when the code freeze begins"
    required: true
  codefreeze-end:
    description: "The date when the code freeze ends"
    required: true
  allowed-paths:
    description: "The paths that are allowed to be modified during the code freeze"
    required: false
  token:
    description: >
      GitHub token for GitHub API requests.
      Users shouldn't need to set this themselves.
    required: true
    default: ${{ github.token }}

runs:
  using: node20
  main: dist/index.js
