version: 2
updates:
  # Update Github actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:00"
      timezone: "America/Los_Angeles"

    cooldown:
      default-days: 5
    groups:
      github-actions:
        patterns:
          - "*"
