# Runs `terraform apply` after doing the required authentication and setup.
# Also builds and pushes a Docker container, if provided.
name: "Apply"

on:
  workflow_call:
    inputs:
      dockerfile:
        description: Name of a dockerfile to build and push before running Terraform.
        required: false
        type: string
      github_ref:
        description: Override of GITHUB_REF environment variable (ie, what branch to run tf against)
        required: false
        type: string
        default: ''
      merge_prs:
        description: Flag to roll up all open PRs
        required: false
        type: boolean
        default: false
      merge_stage_prs:
        description: Flag to roll up open PRs with a "stage" label
        required: false
        type: boolean
        default: false
      post_result_comment:
        description: Whether or not to add a comment to the context's PR with the Terraform command results.
        required: false
        type: boolean
        default: true
      pr_issue_number:
        description: If set, overrides where to send the comments when posting
        required: false
        type: string
        default: ''
      really_actually_use_k8s:
        description: Help with deprecation of k8s parameters
        required: false
        type: boolean
        default: false
      tf_var_json:
        description: A JSON string to write into terraform.tfvars.json when applying.
        required: false
        type: string
      tf_version:
        description: Which version of terraform to use, eg. 1.1.2 or 0.15.5. If unset, reads .terraform-version in the repo root.
        required: false
        type: string
        default: ''
      tf_prefix:
        description: The terraform backend's prefix within the GCS bucket
        required: false
        type: string
      tf_working_directory:
        description: The directory from which to run terraform commands
        required: false
        type: string
    secrets:
      CI_BOT_TOKEN:
        description: GITHUB_TOKEN environment variable to run merge_prs script
        required: false
      CI_BOT_USERNAME:
        description: GITHUB_USERNAME environment variable to run merge_prs script
        required: false
      tf_bucket:
        description: The terraform backend's GCS bucket
        required: true
      gcp_project_id:
        required: true
      gcp_service_account_key:
        required: true
      k8s_cluster_id:
        required: false
      k8s_cluster_zone:
        required: false
      repository:
        description: Repository within Container Registry to push the built Docker image into.
        required: false
      ssh_agent_private_key:
        required: true

jobs:
  Apply:
    env:
      GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
      GITHUB_USERNAME: ${{ secrets.CI_BOT_USERNAME }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref:  ${{ inputs.github_ref }}
          fetch-depth: 0

      - name: User config
        if: ${{ inputs.merge_prs || inputs.merge_stage_prs }}
        run: |-
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Rollup open PRs
        id: rollup_dev
        if: ${{ inputs.merge_prs }}
        run: |-
          git checkout origin/main
          echo "Open PRs to deploy:"
          echo "-----"
          gh pr list --draft=false --base=main --limit=100 --json number,headRefName,author,mergeable \
            -t "{{ range . }}{{ .number }} {{ .headRefName }} {{ .author.login }} {{ .mergeable }}
          {{end}}" | sort -n
          echo "-----"
          gh pr list --draft=false --base=main --limit=100 --json number,headRefName,mergeable \
            -t "{{ range . }}{{ .number }} {{ .headRefName }} {{ .mergeable }}
          {{end}}" | grep MERGEABLE | sort -n | cut -d ' ' -f2 | xargs -I{} -n1 git merge origin/{}

      - name: Rollup open stage PRs
        id: rollup_stage
        if: ${{ inputs.merge_stage_prs }}
        run: |-
          git checkout origin/main
          echo "Open PRs to deploy:"
          echo "-----"
          gh pr list --label=stage --draft=false --base=main --limit=100 --json number,headRefName,author,mergeable \
            -t "{{ range . }}{{ .number }} {{ .headRefName }} {{ .author.login }} {{ .mergeable }}
          {{end}}" | sort -n
          echo "-----"
          gh pr list --label=stage --draft=false --base=main --limit=100 --json number,headRefName,mergeable \
            -t "{{ range . }}{{ .number }} {{ .headRefName }} {{ .mergeable }}
          {{end}}" | grep MERGEABLE | sort -n | cut -d ' ' -f2 | xargs -I{} -n1 git merge origin/{}

      - name: Get current SHA
        id: get_sha
        run: |-
          sha=$(git rev-parse HEAD)
          echo "HEAD is now at SHA: $sha"
          echo "sha=$sha" >> "$GITHUB_OUTPUT"

      - name: Get Terraform Version
        id: get_tf_version
        run: |-
          input_version=${{ inputs.tf_version }}
          if [[ -z $input_version ]]; then
            tf_version=`cat .terraform-version`
            echo "Using .terraform-version: $tf_version"
            echo "tf_version=$tf_version" >> "$GITHUB_OUTPUT"
          else
            echo "Using tf_version from input: $input_version"
            echo "tf_version=$input_version" >> "$GITHUB_OUTPUT"
          fi

      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.ssh_agent_private_key }}

      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.ssh_agent_private_key }}

      - uses: google-github-actions/auth@v1
        with:
          project_id: ${{ secrets.gcp_project_id }}
          credentials_json: ${{ secrets.gcp_service_account_key }}

      - name: Use System GCloud
        uses: google-github-actions/setup-gcloud@v1
        if: ${{ ! inputs.really_actually_use_k8s }}
        with:
          skip_install: True

      - name: Setup GCloud with GKE Auth Plugin
        uses: google-github-actions/setup-gcloud@v1
        if: inputs.really_actually_use_k8s
        with:
          version: '>= 422.0.0'
          install_components: "gke-gcloud-auth-plugin"

      # Get the GKE credentials, so we can plan against the cluster
      - name: get-credentials
        # Workaround to https://github.com/actions/runner/issues/520
        if: inputs.really_actually_use_k8s
        run: |-
          gcloud container clusters get-credentials ${{ secrets.k8s_cluster_id }} --zone ${{ secrets.k8s_cluster_zone }}

      - run: |-
          gcloud --quiet auth configure-docker

      - name: Touch Files
        if: inputs.post_result_comment
        working-directory: ${{ inputs.tf_working_directory }}
        run: |-
          # Ensure files exist for the output script, even if steps fail
          touch apply_output.txt
          touch full_output.txt

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: ${{ steps.get_tf_version.outputs.tf_version }}
          terraform_wrapper: false

      - name: Sanity check
        run: |-
          echo "APP CLIENTID: ${{ secrets.GW_CI_BOT_APP_CLIENTID  }}"

      - name: Get application token
        id: get_application_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GW_CI_BOT_APP_CLIENTID }}
          installation_id: ${{ secrets.GW_CI_BOT_APP_INSTALLATION_ID }}
          private_key: ${{ secrets.GW_CI_BOT_APP_SECRET }}

      - name: Extend Git credentials
        uses: de-vri-es/setup-git-credentials@v2.0.10
        with:
          credentials: https://user:${{ steps.get_application_token.outputs.token }}@github.com

      - name: Terraform Init
        id: init
        run: |-
          terraform init -backend-config="bucket=${{ secrets.tf_bucket }}" -backend-config="prefix=${{ inputs.tf_prefix }}" -reconfigure
        working-directory: ${{ inputs.tf_working_directory }}

      - name: Build and push image
        if: inputs.dockerfile
        uses: docker/build-push-action@v1
        with:
          dockerfile: ${{ inputs.dockerfile }}
          username: _json_key
          password: ${{ secrets.gcp_service_account_key }}
          registry: gcr.io
          repository: ${{ secrets.repository }}
          tags: ${{ steps.get_sha.outputs.sha }}

      - name: Write TFVars
        if: ${{ inputs.tf_var_json }}
        working-directory: ${{ inputs.tf_working_directory }}
        run: |-
          # Write the input to the varfile without substitution
          cat <<- EOF >> terraform.tfvars.json
            ${{ inputs.tf_var_json }}
          EOF

      - name: Terraform Apply
        id: apply
        env:
          TF_VAR_git_sha: ${{ steps.get_sha.outputs.sha }}
        run: |-
          terraform apply --auto-approve --input=false -no-color 2>&1 | tee full_output.txt
          # Use PIPESTATUS to capture errors in terraform plan:
          # See https://linux.samba.narkive.com/Oc6yBphD/clug-tee-eats-the-return-code-of-the-previous-entry-in-the-pipeline#post4
          tf_status=${PIPESTATUS[0]}

          # Trim the preamble
          sed -n '/─────────────────────────────────────────────────────────────────────────────/,$p' full_output.txt > apply_output.txt

          exit $tf_status
        working-directory: ${{ inputs.tf_working_directory }}

      - uses: actions/github-script@v6
        if: inputs.post_result_comment && (success() || failure())
        with:
          script: |
            const fs = require('fs')
            const apply_output = fs.readFileSync('${{ inputs.tf_working_directory }}/apply_output.txt', 'utf8')
            const full_output = fs.readFileSync('${{ inputs.tf_working_directory }}/full_output.txt', 'utf8')

            const issue_number = "${{ inputs.pr_issue_number }}" || context.issue.number
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
            })
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Terraform Apply')
            })

            const output = `## Terraform Apply
            #### Initialization: ️${{ steps.init.outcome }}

            <details open><summary><b>Apply: ${{ steps.apply.outcome }}</b></summary>

            \`\`\`diff
            ${apply_output}
            \`\`\`

            </details>

            <details><summary><i>full apply logs</i></summary>

            \`\`\`diff
            ${full_output}
            \`\`\`

            </details>

            *Requester: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;
            if (botComment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output
            })
            } else {
              github.rest.issues.createComment({
                issue_number: issue_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
            }

